// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiError = { apiVersion: number, code: string, message: string, retryable: boolean, };
