// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationRenameFileSelection } from "./NotationRenameFileSelection";

export type ApplyNotationRenameRequest = { projectId: string, conceptId: string, files: Array<NotationRenameFileSelection>, };
