// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationRenameFileResult } from "./NotationRenameFileResult";

export type ApplyNotationRenameResult = { apiVersion: number, projectId: string, conceptId: string, files: Array<NotationRenameFileResult>, };
