// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildOutputStream } from "./BuildOutputStream";
import type { OperationId } from "./OperationId";

export type BuildOutput = { apiVersion: number, projectId: string, operationId: OperationId, stream: BuildOutputStream, text: string, };
