// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildPhase } from "./BuildPhase";
import type { BuildReason } from "./BuildReason";
import type { Diagnostic } from "./Diagnostic";
import type { LatexEngine } from "./LatexEngine";
import type { OperationId } from "./OperationId";

export type BuildState = { apiVersion: number, projectId: string, operationId: OperationId, phase: BuildPhase, reason: BuildReason, rootDocument: string, engine: LatexEngine, elapsedMs: bigint | null, exitCode: number | null, logTruncated: boolean, rawLogAvailable: boolean, diagnostics: Array<Diagnostic>, pdfAvailable: boolean, lastSuccessfulOperationId: OperationId | null, message: string | null, };
