// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatexEngine } from "./LatexEngine";
import type { ResolutionProvenance } from "./ResolutionProvenance";

export type BuildConfiguration = { apiVersion: number, projectId: string, rootDocument: string, rootProvenance: ResolutionProvenance, engine: LatexEngine, engineProvenance: ResolutionProvenance, };
