// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId";

export type BuildLog = { apiVersion: number, projectId: string, operationId: OperationId, text: string, truncated: boolean, };
