// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogMatchKind } from "./CatalogMatchKind";
import type { CommandEntry } from "./CommandEntry";

export type CatalogSearchHit = { entry: CommandEntry, score: number, matchKind: CatalogMatchKind, contextMatch: boolean, requirementsSatisfied: boolean, };
