// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandContext } from "./CommandContext";

export type CatalogSearchQuery = { query: string, context: CommandContext | null, availablePackages: Array<string>, limit: number, };
