// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandEntry } from "./CommandEntry";

export type CommandCatalog = { apiVersion: number, schemaVersion: number, catalogVersion: string, entries: Array<CommandEntry>, };
