// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogProvenance } from "./CatalogProvenance";
import type { CommandContext } from "./CommandContext";
import type { CommandExample } from "./CommandExample";
import type { PackageRequirement } from "./PackageRequirement";

export type CommandEntry = { id: string, command: string, displayName: string, summary: string, concepts: Array<string>, synonyms: Array<string>, requirements: Array<PackageRequirement>, signature: string, snippet: string, examples: Array<CommandExample>, documentationUrl: string, contexts: Array<CommandContext>, provenance: CatalogProvenance, };
