// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticPhase } from "./DiagnosticPhase";
import type { DiagnosticSeverity } from "./DiagnosticSeverity";
import type { DiagnosticSourceRange } from "./DiagnosticSourceRange";

export type Diagnostic = { code: string, severity: DiagnosticSeverity, phase: DiagnosticPhase, message: string, source: DiagnosticSourceRange | null, };
