// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectiveNotationConcept } from "./EffectiveNotationConcept";

export type EffectiveNotationProfile = { apiVersion: number, profileVersion: number, name: string, projectId: string | null, concepts: Array<EffectiveNotationConcept>, };
