// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationPreferenceSource } from "./NotationPreferenceSource";

export type EffectiveNotationConcept = { id: string, label: string, preferredForm: string, declaredForms: Array<string>, source: NotationPreferenceSource, };
