// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTreeEntry } from "./FileTreeEntry";

export type FileTreePage = { apiVersion: number, directory: string, entries: Array<FileTreeEntry>, truncated: boolean, };
