// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTreeEntryKind } from "./FileTreeEntryKind";

export type FileTreeEntry = { name: string, relativePath: string, kind: FileTreeEntryKind, isSymlink: boolean, accessible: boolean, hidden: boolean, generated: boolean, };
