// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexIssueCode } from "./IndexIssueCode";
import type { IndexSourceRange } from "./IndexSourceRange";

export type IndexIssue = { code: IndexIssueCode, message: string, relativePath: string | null, range: IndexSourceRange | null, };
