// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileIndexStatus } from "./FileIndexStatus";
import type { IndexIssue } from "./IndexIssue";
import type { IndexRecord } from "./IndexRecord";

export type IndexedFile = { relativePath: string, fingerprint: string, status: FileIndexStatus, records: Array<IndexRecord>, issues: Array<IndexIssue>, };
