// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexConfidence } from "./IndexConfidence";
import type { IndexProvenance } from "./IndexProvenance";
import type { IndexRecordKind } from "./IndexRecordKind";
import type { IndexSourceRange } from "./IndexSourceRange";

export type IndexRecord = { kind: IndexRecordKind, name: string, target: string | null, range: IndexSourceRange, confidence: IndexConfidence, provenance: IndexProvenance, };
