// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId";

export type InverseSynctexRequest = { projectId: string, operationId: OperationId, page: number, x: number, y: number, };
