// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexSourceRange } from "./IndexSourceRange";

export type NotationUsage = { conceptId: string, form: string, preferred: boolean, range: IndexSourceRange, };
