// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotationConcept = { id: string, label: string, preferredForm: string, declaredForms: Array<string>, };
