// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexSourceRange } from "./IndexSourceRange";
import type { NotationDiagnosticCode } from "./NotationDiagnosticCode";
import type { NotationDiagnosticSeverity } from "./NotationDiagnosticSeverity";

export type NotationDiagnostic = { code: NotationDiagnosticCode, severity: NotationDiagnosticSeverity, conceptId: string, conceptLabel: string, message: string, relativePath: string, fingerprint: string, range: IndexSourceRange, observedForm: string, preferredForm: string, evidenceForms: Array<string>, };
