// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationUsage } from "./NotationUsage";

export type NotationFileUsage = { relativePath: string, fingerprint: string, usages: Array<NotationUsage>, truncated: boolean, };
