// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationRenameFilePreview } from "./NotationRenameFilePreview";

export type NotationRenamePreview = { apiVersion: number, schemaVersion: number, projectId: string, conceptId: string, preferredForm: string, indexGeneration: bigint, files: Array<NotationRenameFilePreview>, incomplete: boolean, };
