// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationRenameFileStatus } from "./NotationRenameFileStatus";

export type NotationRenameFileResult = { relativePath: string, status: NotationRenameFileStatus, message: string | null, fingerprint: string | null, };
