// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationRenameEdit } from "./NotationRenameEdit";

export type NotationRenameFilePreview = { relativePath: string, fingerprint: string, originalText: string, revisedText: string, edits: Array<NotationRenameEdit>, };
