// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationConceptOverride } from "./NotationConceptOverride";

export type ProjectNotationOverrides = { version: number, concepts: Array<NotationConceptOverride>, };
