// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationSuppression } from "./NotationSuppression";

export type ProjectNotationSuppressions = { version: number, items: Array<NotationSuppression>, };
