// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildPermission } from "./BuildPermission";

export type ProjectPermission = { permission: BuildPermission, allowed: boolean, consequence: string, };
