// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexCompleteness } from "./IndexCompleteness";
import type { IndexIssue } from "./IndexIssue";
import type { IndexedFile } from "./IndexedFile";
import type { ScannerLimits } from "./ScannerLimits";

export type ProjectIndex = { apiVersion: number, schemaVersion: number, projectId: string, generation: bigint, completeness: IndexCompleteness, scannerLimits: ScannerLimits, files: Array<IndexedFile>, issues: Array<IndexIssue>, };
