// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationDiagnostic } from "./NotationDiagnostic";

export type ProjectNotationDiagnostics = { apiVersion: number, schemaVersion: number, profileVersion: number, projectId: string, indexGeneration: bigint, diagnostics: Array<NotationDiagnostic>, suppressedCount: number, incomplete: boolean, };
