// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotationFileUsage } from "./NotationFileUsage";

export type ProjectNotationUsage = { apiVersion: number, schemaVersion: number, profileVersion: number, projectId: string, indexGeneration: bigint, files: Array<NotationFileUsage>, incomplete: boolean, };
