// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecoverySnapshot = { apiVersion: number, snapshotVersion: number, projectId: string, relativePath: string, text: string, baseFingerprint: string, revision: bigint, updatedAtMs: bigint, };
