// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootDocumentCandidate } from "./RootDocumentCandidate";

export type RootDocumentCandidates = { apiVersion: number, candidates: Array<RootDocumentCandidate>, selected: string | null, };
