// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScannerLimits = { maxProjectFiles: number, maxTotalBytes: bigint, maxFileBytes: bigint, maxRecordsPerFile: number, maxBraceDepth: number, maxCommandBytes: number, };
