// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId";

export type SynctexSourcePosition = { apiVersion: number, projectId: string, operationId: OperationId, relativePath: string, line: number, column: number | null, };
