// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextDocument = { apiVersion: number, relativePath: string, text: string, fingerprint: string, sizeBytes: bigint, };
