// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolchainBinary } from "./ToolchainBinary";
import type { ToolchainStatus } from "./ToolchainStatus";

export type ToolchainReadiness = { apiVersion: number, status: ToolchainStatus, toolchainId: string | null, texliveYear: number | null, texliveRevision: number | null, platform: string | null, binaries: Array<ToolchainBinary>, message: string | null, repairable: boolean, };
